# Generated by Django 3.2.3 on 2021-07-12 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('Train_name', models.CharField(max_length=20)),
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('maxSeats', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('Trip_name', models.CharField(max_length=20)),
                ('trid', models.AutoField(primary_key=True, serialize=False)),
                ('src', models.CharField(max_length=30)),
                ('dest', models.CharField(max_length=30)),
                ('availableSeats', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField()),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.train')),
            ],
        ),
    ]
